// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Channel         *string           `json:",omitempty"`
	Guid            *string           `json:",omitempty"`
	ListQueryFilter *string           `json:",omitempty"`
	ListQuerySorter *string           `json:",omitempty"`
	Variables       map[string]string `json:",omitempty"`
}
